import { GoogleGenerativeAI } from '@google/generative-ai';

export interface OriginalityResult {
    score: number; // 0-100
    informationGain: number; // 0-100 — how much unique value this adds
    derivativeRisk: 'low' | 'medium' | 'high';
    uniqueAngles: string[]; // Suggestions for making content more original
    genericPhrases: string[]; // Phrases that are too common / AI-sounding
    verdict: string; // One-line assessment
}

/**
 * Score the originality of content to avoid the "infinite AI derivatives" trap.
 * Checks for information gain, derivative risk, and suggests unique angles.
 */
export async function scoreOriginality(
    content: string,
    topic: string
): Promise<OriginalityResult> {
    const geminiKey = process.env.GOOGLE_API_KEY || process.env.GEMINI_API_KEY;

    if (!geminiKey) {
        return fallbackOriginalityCheck(content);
    }

    const genAI = new GoogleGenerativeAI(geminiKey);
    const model = genAI.getGenerativeModel({ model: 'gemini-2.5-flash' });

    const result = await model.generateContent(
        `You are a content quality expert focused on "information gain" — the concept that content which adds unique value (original data, personal experience, proprietary insights, contrarian takes) performs better in AEO.

Analyze this content about "${topic}" for originality and information gain:

"""
${content.slice(0, 4000)}
"""

Evaluate:
1. Information Gain (0-100): Does this content add UNIQUE value beyond what's already widely available? Original research, proprietary data, personal experience, and contrarian insights score high. Generic summaries of common knowledge score low.
2. Derivative Risk (low/medium/high): Could this content have been generated by summarizing other AI-generated content? If it reads like a typical AI summary with no original perspective, it's HIGH risk.
3. Generic Phrases: Identify 3-5 phrases that are overly common or "AI-sounding" that could be replaced.
4. Unique Angles: Suggest 3-5 ways this content could be made MORE original (e.g., "Add a case study from a real customer", "Include your own performance data").

Return ONLY valid JSON:
{
  "score": 0-100,
  "informationGain": 0-100,
  "derivativeRisk": "low|medium|high",
  "uniqueAngles": ["suggestion 1", "suggestion 2"],
  "genericPhrases": ["phrase 1", "phrase 2"],
  "verdict": "One-line summary of content originality"
}`
    );

    const text = result.response.text();
    const jsonMatch = text.match(/\{[\s\S]*\}/);

    if (!jsonMatch) {
        return fallbackOriginalityCheck(content);
    }

    return JSON.parse(jsonMatch[0]) as OriginalityResult;
}

/**
 * Simple heuristic-based originality check (no AI needed)
 */
function fallbackOriginalityCheck(content: string): OriginalityResult {
    const lowerContent = content.toLowerCase();

    // Detect generic AI-generated phrases
    const genericPhrases: string[] = [];
    const genericPatterns = [
        'in conclusion', 'it is important to note', 'in today\'s world',
        'ultimately', 'at the end of the day', 'there are several',
        'it\'s worth noting', 'one of the most important', 'first and foremost',
        'in summary', 'as we have seen', 'it goes without saying',
        'needless to say', 'without further ado', 'that being said',
    ];

    for (const phrase of genericPatterns) {
        if (lowerContent.includes(phrase)) {
            genericPhrases.push(phrase);
        }
    }

    // Check for diversity of content (data, numbers, specific examples)
    const hasNumbers = /\d{2,}/.test(content);
    const hasQuotes = content.includes('"') && content.split('"').length > 4;
    const hasSpecificBrands = /\b[A-Z][a-z]+(?:\.com|\.io|\.ai)\b/.test(content);

    let score = 50;
    let informationGain = 50;

    // Penalties
    score -= genericPhrases.length * 5;
    informationGain -= genericPhrases.length * 7;

    // Bonuses
    if (hasNumbers) { score += 10; informationGain += 10; }
    if (hasQuotes) { score += 10; informationGain += 10; }
    if (hasSpecificBrands) { score += 5; informationGain += 5; }

    score = Math.max(0, Math.min(100, score));
    informationGain = Math.max(0, Math.min(100, informationGain));

    const derivativeRisk = genericPhrases.length > 4 ? 'high' : genericPhrases.length > 2 ? 'medium' : 'low';

    return {
        score,
        informationGain,
        derivativeRisk,
        uniqueAngles: [
            'Add original data or statistics from your own experience',
            'Include a specific case study or customer story',
            'Share a contrarian or unexpected perspective',
        ],
        genericPhrases,
        verdict: `Content has a ${derivativeRisk} derivative risk. ${genericPhrases.length > 0 ? `Found ${genericPhrases.length} generic phrases.` : 'Reasonably original.'}`,
    };
}
